# runs npm check on the repo
name: Check
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Run npm check
        run: npm run check
        env:
          CLOUDFLARE_ACCOUNT_ID: 0e6d466dd96fb5b35ed0748ee280321f # webmaster@ieeetamu.org
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
